### ISSUE TITLE
Not compatible?

### ISSUE THREAD

**Issue by nilskp** [release-lab/vscode-whatchanged#1]
![image](https://user-images.githubusercontent.com/74843/136283122-9aa4fd92-8ad0-40ee-b0c4-23a27853d27d.png)

**Comment by axetroy** [comment]
Yes. you need to upgrade to `^1.61.0`

https://github.com/release-lab/vscode-whatchanged/blob/06619bc50642b825658fdbfa9c8371eed66376dd/package.json#L7-L9

**Comment by nilskp** [comment]
Doesn't seem it's released yet, at least not for me.
![image](https://user-images.githubusercontent.com/74843/136383306-6c83f610-42cc-49cd-addb-86f30aa675c0.png)

**Comment by nilskp** [comment]
Thanks.
